### ISSUE TITLE
Holder Metrics endpoint

### ISSUE THREAD

**Issue by GoodforGod** [GoodforGod/bloxy-api#7]
Add support for new tokens holder_metrics endpoint

**Additional context**
Token API

**Comment by 1623csK** [comment]
Is just starting..

**Comment by GoodforGod** [comment]
Also adding given endpoint from Token API
https://bloxy.info/api_method_calls/token?method=token_correlated_addresses

**Comment by GoodforGod** [comment]
Released in 1.2.0
